### ISSUE TITLE
Issue pulling WMS capabilities after update from 4.6 to 5.4

### ISSUE THREAD

**Issue by bsroth** [Unidata/tds#413] opened 2023-08-31 14:01 UTC
Hello,

I'm hoping someone can help me with this we have an application that pulls WMS data from THREDDS and after upgrading we are seeing the following on some data sets.

<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd">
<ServiceException> Problem creating dataset bypass/CREATE-IP/reanalysis/MERRA2/mon/atmos/psl.ncml at file:/usr/local/tomcat/content/thredds/idd/CREATE-IP/reanalysis/MERRA2/mon/atmos/psl.ncml Cause: Coordinate values must increase or decrease monotonically </ServiceException>
</ServiceExceptionReport>

This data worked with 4.6, am I missing something or is the data no longer compatible with WMS

Brian

**Comment by bsroth** [comment] 2023-08-31 14:35
In addition the data that is trying to be pulled is through godiva2 and the godiva3 viewer is not working with 

Error contacting server

**Comment by haileyajohnson** [comment] 2023-08-31 18:03
Hi! This is a known issue, unfortunately: https://github.com/Unidata/netcdf-java/issues/1060
It is fixed in the latest snapshot release (5.5-SNAPSHOT) for 1D coordinate variables, but not yet for 2D variables.
Can you elaborate on your second issue? What do you mean by the data pulled is through godiva2?

**Comment by bsroth** [comment] 2023-08-31 18:06
Dis reguard the second issue that is an issue with our loadbalancer/proxy.

**Comment by haileyajohnson** [comment] 2023-08-31 18:08
thank you for the update! I am going to close this issue as a duplicate of https://github.com/Unidata/netcdf-java/issues/1060, you can follow along there for updates as we work on the issue.

**Closed by haileyajohnson** 2023-08-31 18:08 UTC
